### ISSUE TITLE
RSS feed does not 'show' the latest post

### ISSUE THREAD

**Issue by ddotlic** [arzg/website#4]
Hi,

I'm enjoying your series on language construction in Rust! It's well written and engaging, intersecting with two of my interests: Rust and parsing/compiler construction.

Anyway, I subscribed to the feed today but noticed that my feed software (Feedly) shows no articles at all (typically it'll show a few recent ones, for some value of "recent"). Forcing "show all articles" displays them all except the latest one from January 2021.

Looking at the actual atom feed, I noticed a small discrepancy which **might** explain this: the feed's `lastBuildDate` is 21st of December 2020 yet the newest article is 24th of January 2021.

Feedly seems to stop considering articles published _after_ the feed's `lastBuildDate`. I'm not sure if this is a bug in Feedly, or a bug in your feed generator (based on the atom feed, looks like it's Hugo).

This is just an FYI; it _seems_ this may lead to people subscribed to your feed over Feedly (a large service) to never again be notified about the new post(s) - including me - which would be a shame since the content is really good.

Keep up the good work and greetings from Europe!

Cheers.

**Comment by lunacookies** [comment]
Huh, that is very weird. Looking at [the code](https://github.com/arzg/website/blob/17461cabbc1ea06fdc7353632db52b06a6648f18/layouts/_default/rss.xml#L29), it seems like it just pulls from the current date. Why, then, did the date not change when the site rebuilt?

According to [the w3schools RSS reference](https://www.w3schools.com/XML/xml_rss.asp#rssref), the `lastBuildDate` field is optional. Would there be any downside to removing it?

**Comment by ddotlic** [comment]
@arzg I haven’t checked the atom spec yet, just reporting the situation “from the terrain” 😉  IOW, the problem may be unrelated to that field, but it’s real - the “Reeder” iOS app sees no posts whatsoever (it pulls from Feedly). Something seems to be amiss.

**Comment by lunacookies** [comment]
Hmm, I might rewrite `rss.xml` from scratch to follow the spec. It originated from me copy-pasting it from the Hugo repo and making a small change (I believe it was removing certain Unicode characters that are disallowed by RSS for some reason).

Thanks for the compliments by the way, they mean a lot :)

**Comment by ddotlic** [comment]
Additionally, the W3C feed validator considers the feed valid. Really weird. Looks more like a bug in Feedly and/or Reeder, but both are very stable and well-known apps/services in this space...

**Comment by ddotlic** [comment]
@arzg I thought Hugo generated it all for you - while it’s not a blog platform per-se, it’s often used in that context. Or, you could switch to a Rust based generator like Zola 😛

**Comment by lunacookies** [comment]
I just pushed a change that removed a few fields from the RSS field, including `lastBuildDate` – can you try again?

**Comment by ddotlic** [comment]
@arzg This was quick - the feed is now malformed XML, the first character being `&lt;` which is XML encoding of `<` 😄so I wouldn't call this _better_ 😃

**Comment by lunacookies** [comment]
🤦 I’ve fixed this in 96a969a. Does it work now?

**Comment by ddotlic** [comment]
@arzg The feed is valid now, but the Feedly neither the Reeder app "see" the latest post still. I checked if there was some kind of limit on the number of posts in the feed spec, there doesn't seem to be one.
We could revisit next time you post something, though I may not see it due to this issue 😉 
But if you post a comment to this issue, I'll re-check (will be notified by GitHub).

**Comment by lunacookies** [comment]
I posted a new article earlier today in 06660f8, so I guess you didn’t see that? 😆

**Comment by ddotlic** [comment]
@arzg No, it did not show up. I just forced a refresh and it's not there. A few hours ago, I also tried removing then re-adding the feed.

Using the online Feedly browser, it's adamant that there's nothing after 21st of December 2020.

**Comment by lunacookies** [comment]
I just realised that I mistyped the year as 2020 instead of 2021 so it probably went to the bottom of the feed.

<img width="545" alt="Screen Shot 2021-01-27 at 9 44 25 pm" src="https://user-images.githubusercontent.com/31783266/105980342-d52b5c80-60e8-11eb-860b-2e915c034b37.png">

**Comment by lunacookies** [comment]
Fixed in f4952fb.

**Comment by ddotlic** [comment]
@arzg ~~LOL, but the same applies to the latest post 😃 So both are _still_ not showing up.~~
My bad, the latest post is OK, but downloading the feed still shows the post 19 from 2020. I'll try some time later (in an hour).

**Comment by ddotlic** [comment]
Additionally, the post does not show at the bottom of the feed, seems to be discarded by the reader(s). As usual, we were _way_ overthinking this 😉 the problem must have been the date...

**Comment by ddotlic** [comment]
@arzg No dice, the Feedly either heavily caches the fetched XML or has a bug (less likely). I suggest we simply let this be, I'll try again, say, tomorrow. I'm stubborn like that 🤣

**Comment by lunacookies** [comment]
> As usual, we were way overthinking this 😉

Yep, happens way too often 😄

**Comment by lunacookies** [comment]
> I'll try again, say, tomorrow.

Alright, we’ll see how it goes. This is a very weird bug, for sure.

**Comment by ddotlic** [comment]
@arzg Success! The issue with Feedly must have been aggressive caching server-side, so even when I forced a "refresh" of the feed, they'd do nothing immediately. Just came back to the Feedly browser _and_ the Reeder app and they both show 2 new posts for your blog series. 🎉 Cheers!

**Comment by lunacookies** [comment]
Glad to know the RSS feed finally works!
